name: lawrencewalters
favicon: null
layout_spectrum: 0.6251124346163124
typography_spectrum: 0.720184040023014
title: Managing software development
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-60590037-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#15110e'
    - '#8cb7da'
    - '#eeb273'
    - '#433534'
    - '#a26f5a'
  brandStrength: 0.8125
  lightness: 0.8335409548599273
  saturation: 0.2614141369704157
  rhythmicContrast: 0.04266304359771311
purpose: []
